### ISSUE TITLE
Getting issue related internal Permission issue in Your call SDK. 

### ISSUE THREAD

**Issue by ankurbhut** [cometchat/cometchat-uikit-android-kotlin#10]
> Important dates for QUERY_ALL_PACKAGES permission declaration

> If your app does not require the use of the QUERY_ALL_PACKAGES permission, you must remove the permission from your app manifest. For apps that require this permission, you can now submit a declaration form in Play Console.
> 
> You'll need to provide:
> 
>  i). A description of the core feature in your app that requires this permission
>  ii). A short video showing the core feature in your app that requires this permission
> To prepare for the questions you'll be required to answer, review this [Help Center](https://support.google.com/googleplay/android-developer/answer/9214102) article.
> 
> Starting July 12, you will not be able to submit new apps or app updates if the declaration is missing. You have until July 12 to submit the declaration or remove the permission from your app manifest. Apps that fail to meet the [policy requirements](https://support.google.com/googleplay/android-developer/answer/9888170#package-vis) or do not submit the declaration form may be removed from Google Play starting July 12.

So please remove or update it accordingly. As well as if it is more important then please guide us to approve my app with the use of your SDK. Provide Detail Info for use of that permission. So I can update to google for use.

**Comment by darshanbhanushali** [comment]
Hello @ankurbhut ,

We had QUERY_ALL_PACKAGES permission in Calls manifest file. We have removed it and released a new beta version.﻿
﻿You will need to change the version of Calls SDK to `2.1.2-beta8` in `build.gradle` file of **uikit-kotlin** library & **app**.
﻿

**Comment by ankurdevstree** [comment]
Thanks for the update.
